name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Update otomatis tiap jam 12 malem
  workflow_dispatch: # Biar lu bisa klik "Run" manual kapan aja
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # OPTIONS
          user: claycuy
          template: classic
          base: "" # KOSONGIN biar statistik commit/stars/PR ilang semua
          
          # PLUGIN LANGUAGES (Buat gantiin "Top Language")
          plugin_languages: yes
          plugin_languages_ignored: html, css # Buang bahasa yang gak penting
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          
          # OUTPUT
          filename: github-metrics.svg # Nama file yang bakal di-generate
